version: '3'
services:
  redis:
    build:
      context: ./redis-vector-db
      dockerfile: Dockerfile
    volumes:
      - ./redis-vector-db/data:/data/
    ports:
      - 6379:6379
      - 8001:8001
  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    volumes:
      - ./vecsim:/home/jovyan/vecsim
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
